### ISSUE TITLE
sprite animation using nflib

### ISSUE THREAD

**Issue by pomegrenade** [dado3212/among-us-ds#1]
Hello, not an issue with this project per se, but I saw that you got animation working well on this homebrew and was wondering if you had a method of doing this sprite animation in 4 directions using NFLib? Please do let me know, and thanks in advance!

**Comment by dado3212** [comment]
Unfortunately I don't have a ton of experience with this and was mostly hacking this together. Really can't recommend the right way to do anything other than some liberal copy-paste and glue. Feel free to use anything in this repo, but can't give any great advice.
